function errorbarwidth(hE,width)
hE_c                   = ...
    get(hE     , 'Children'    );
errorbarXData          = ...
    get(hE_c(2), 'XData'       );
errorbarXData(4:9:end) = ...
    errorbarXData(1:9:end) - width;
errorbarXData(7:9:end) = ....
    errorbarXData(1:9:end) - width;
errorbarXData(5:9:end) = ...
    errorbarXData(1:9:end) + width;
errorbarXData(8:9:end) = ...
    errorbarXData(1:9:end) + width;
set(hE_c(2), 'XData', errorbarXData);
end