% Wrapper script for calling the function AllTensors.m for the entire time
% history series of a radiation recrystallization experimental run
clear all; close all; clc;
[PixSize,VolFrac,D,E,MeanStrucThick,MeanStrucSep,idx,Tr,TrCi,MIL,MILCi,F2,F2Ci,...
    F4,F4Ci,bondRad,grainRad,meanBondRad,meanGrainRad,coordNum,shapeFac]...
    = AllTensors(2);