% RunContactTesnor.m
[F2,F2Ci,F4,F4Ci,bondRad,grainRad,meanBondRad,meanGrainRad,...
    coordNum,shapeFac,idx,endtime,spatialLabel]...
    = ContactTensor(1,1,1,'C:\Users\David\Documents\MSU Research\Doctoral Work\Mechanical Testing\Radiation Recrystallization\PhD Work\Spheres\');